version: "3"

services:
    rabbitmq:
        image: rabbitmq:3.9.13-management-alpine
        container_name: "rabbitmq"
        restart: always
        environment:
            - "RABBITMQ_DEFAULT_PASS=username"
            - "RABBITMQ_DEFAULT_USER=password"
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - rabbitmq_go_net
    db:
        image: "postgres:latest"
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: yourbank_db
        ports:
            - "5432:5432"
volumes:
    pgdata:
networks:
    rabbitmq_go_net:
        driver: bridge
